[features]
seeds = false
skip-lint = false

[programs.localnet]
degen_derby = "Dky8DpKsA4LgCMs1YFUPhrvYE1C1FbwZeFjHSHzXzpzv"

[programs.devnet]
degen_derby = "Dky8DpKsA4LgCMs1YFUPhrvYE1C1FbwZeFjHSHzXzpzv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "../../authority.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
