[features]
seeds = false
skip-lint = false

[programs.localnet]
shadow_poker = "3mQcoeWan1JqBJRp6717NR7U8U87fujG2AjB4Pu8vu2s"

[programs.devnet]
shadow_poker = "3mQcoeWan1JqBJRp6717NR7U8U87fujG2AjB4Pu8vu2s"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/user/house.fun/authority.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
