[features]
seeds = false
skip-lint = false
skip-idl = true

[programs.localnet]
shadow_poker = "5YScsLMogjS2JHeXPfQjxEHoAK17RGMCauo1rj343RWD"

[programs.devnet]
shadow_poker = "5YScsLMogjS2JHeXPfQjxEHoAK17RGMCauo1rj343RWD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "../../house-fun-app/authority.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
