[features]
seeds = false
skip-lint = false

[programs.localnet]
shadow_poker = "HT1ro9KCKv3bzrvrtjonrMWuHZeNYFPvscPWy8bMaogx"
degen_derby = "G1cMMP2dDQNBDs1jDceKpLLAPiANympZUbAsLyMCXZkB"
fight_club = "5BZ86FTWQGrFnMLk17D882N7shNqoVuohbkKo2Ljt7GN"

[programs.devnet]
shadow_poker = "HT1ro9KCKv3bzrvrtjonrMWuHZeNYFPvscPWy8bMaogx"
degen_derby = "G1cMMP2dDQNBDs1jDceKpLLAPiANympZUbAsLyMCXZkB"
fight_club = "5BZ86FTWQGrFnMLk17D882N7shNqoVuohbkKo2Ljt7GN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "deployer-key.json"

[workspace]
members = [
    "programs/shadow-poker/programs/shadow-poker",
    "programs/degen-derby/programs/degen-derby",
    "programs/fight-club/programs/fight-club"
]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
